In [67]:
import pandas as pd

In [68]:
df=pd.read_csv("C:/Users/histan/Desktop/NTU AI Program/AI Lab/Lesson4 20210803/bankruptcy (balance).csv")

In [69]:
print(df)

          Attr1     Attr2     Attr3     Attr4     Attr5     Attr6     Attr7  \
0     -0.031545 -0.091313 -0.040269 -0.013529  0.007406 -0.016047 -0.000264   
1     -0.231729 -0.049448  0.304381 -0.080975  0.007515 -0.016047 -0.034963   
2     -0.058602  0.065060 -0.488404 -0.189489  0.006572 -0.016047 -0.004954   
3     -0.069376  0.044641 -0.181684 -0.140032  0.007477 -0.010915 -0.005599   
4      0.236424 -0.051912  0.678337 -0.014680  0.007879 -0.016047  0.057418   
...         ...       ...       ...       ...       ...       ...       ...   
19589 -0.232279  0.068074 -0.705143 -0.222192  0.005776 -0.013017 -0.035058   
19590 -0.096004 -0.058023 -0.445118 -0.175664  0.006880 -0.016047 -0.010788   
19591 -0.091435 -0.052463 -0.204797 -0.133794  0.006687 -0.016047 -0.010141   
19592 -0.676310  0.245391 -3.155124 -0.304241 -0.001384 -0.037922 -0.105756   
19593 -0.704013  0.098177 -1.208785 -0.246893  0.005521 -0.016047 -0.122524   

          Attr8     Attr9    Attr10  ...    Attr56 

In [70]:
X=df.loc[:,["Attr1","Attr2","Attr3"]]

In [71]:
print(X)

          Attr1     Attr2     Attr3
0     -0.031545 -0.091313 -0.040269
1     -0.231729 -0.049448  0.304381
2     -0.058602  0.065060 -0.488404
3     -0.069376  0.044641 -0.181684
4      0.236424 -0.051912  0.678337
...         ...       ...       ...
19589 -0.232279  0.068074 -0.705143
19590 -0.096004 -0.058023 -0.445118
19591 -0.091435 -0.052463 -0.204797
19592 -0.676310  0.245391 -3.155124
19593 -0.704013  0.098177 -1.208785

[19594 rows x 3 columns]


In [72]:
Y=df.loc[:,["class"]]

In [73]:
print(Y)

       class
0          0
1          0
2          0
3          0
4          0
...      ...
19589      1
19590      1
19591      1
19592      1
19593      1

[19594 rows x 1 columns]


In [74]:
from sklearn.model_selection import train_test_split

In [75]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

In [76]:
print(X_train,X_test,Y_train,Y_test)

          Attr1     Attr2     Attr3
3165  -0.063917 -0.016438  1.427104
9688   0.144513 -0.058880  1.355604
17293 -0.053830  0.084637 -0.194778
129   -0.401868  0.046114 -0.917633
5964  -0.030797 -0.078054  0.701084
...         ...       ...       ...
6839  -1.081330  0.311871 -3.524263
16177 -0.479072  0.613320 -1.488545
10935  0.094027 -0.025513  1.131583
1027  -0.001145 -0.043392 -0.454862
9554  -0.186169  0.054624  0.496599

[13715 rows x 3 columns]           Attr1     Attr2     Attr3
12661 -0.167798 -0.063493 -0.453676
13593 -0.066560  0.107060 -1.970184
13055 -0.330138  0.051592 -0.901138
17663  0.018665  0.057432  0.601546
9390  -0.084903  0.109803 -1.029424
...         ...       ...       ...
17902 -0.080088 -0.011525 -0.169116
3480   0.260047  0.013146  0.538482
16212 -0.067338  0.021658  0.318040
13838 -0.109416  0.124487 -1.772287
10663 -0.111683  0.025443 -0.433778

[5879 rows x 3 columns]        class
3165       0
9688       0
17293      1
129        0
5964       0
...    

In [77]:
from tensorflow.keras.models import Sequential

In [78]:
from tensorflow.keras.layers import Dense, Dropout

In [79]:
from sklearn.metrics import confusion_matrix

In [80]:
dir(Sequential)

['_TF_MODULE_IGNORED_PROPERTIES',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_trackable',
 '_add_variable_with_custom_getter',
 '_assert_compile_was_called',
 '_assert_weights_created',
 '_autographed_call',
 '_build_graph_network_for_inferred_shape',
 '_call_accepts_kwargs',
 '_call_arg_was_passed',
 '_call_fn_arg_defaults',
 '_call_fn_arg_positions',
 '_call_fn_args',
 '_call_full_argspec',
 '_cast_single_input',
 '_check_call_args',
 '_checkpoint_dependencies',
 '_clear_losses',
 '_compile_was_called',
 '_compute_dtype',
 '_compute_tensor_usage_count',
 '_configure_steps_per_execution',
 '_conform_to_reference

In [81]:
import tensorflow.keras.models

In [82]:
dir(tensorflow.keras.models)

['Model',
 'Sequential',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'clone_model',
 'load_model',
 'model_from_config',
 'model_from_json',
 'model_from_yaml',
 'save_model']

In [83]:
model= Sequential()

In [84]:
model.add(Dense(10,input_dim=3,activation="relu"))
model.add(Dropout(0.2))

In [85]:
model.add(Dense(8,activation="relu"))
model.add(Dropout(0.3))

In [86]:
model.add(Dense(6,activation="relu"))
model.add(Dropout(0.2))

In [87]:
model.add(Dense(1,activation="sigmoid"))

In [88]:
model.compile(loss='binary_crossentropy',optimizer="Adamax",metrics=["accuracy"])

In [89]:
model.fit(X_train,Y_train,batch_size=10,epochs=30,verbose=1)

Epoch 1/30
1372/1372 [==============================] - 1s 455us/step - loss: 0.6826 - accuracy: 0.5972
Epoch 2/30
1372/1372 [==============================] - 1s 449us/step - loss: 0.6744 - accuracy: 0.6116
Epoch 3/30
1372/1372 [==============================] - 1s 459us/step - loss: 0.6675 - accuracy: 0.6240
Epoch 4/30
1372/1372 [==============================] - 1s 452us/step - loss: 0.6530 - accuracy: 0.6388
Epoch 5/30
1372/1372 [==============================] - 1s 464us/step - loss: 0.6449 - accuracy: 0.6512
Epoch 6/30
1372/1372 [==============================] - 1s 458us/step - loss: 0.6412 - accuracy: 0.6576
Epoch 7/30
1372/1372 [==============================] - 1s 457us/step - loss: 0.6356 - accuracy: 0.6648
Epoch 8/30
1372/1372 [==============================] - 1s 465us/step - loss: 0.6301 - accuracy: 0.6705
Epoch 9/30
1372/1372 [==============================] - 1s 467us/step - loss: 0.6311 - accuracy: 0.6741
Epoch 10/30
1372/1372 [==============================] - 1s 460u

In [90]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 10)                40        
_________________________________________________________________
dropout_6 (Dropout)          (None, 10)                0         
_________________________________________________________________
dense_11 (Dense)             (None, 8)                 88        
_________________________________________________________________
dropout_7 (Dropout)          (None, 8)                 0         
_________________________________________________________________
dense_12 (Dense)             (None, 6)                 54        
_________________________________________________________________
dropout_8 (Dropout)          (None, 6)                 0         
_________________________________________________________________
dense_13 (Dense)             (None, 1)                

In [91]:
model.weights

[<tf.Variable 'dense_10/kernel:0' shape=(3, 10) dtype=float32, numpy=
 array([[-0.0886283 , -0.30077845,  0.29169238,  0.78571767, -0.60677683,
          0.14088129,  0.02648067, -1.3466598 ,  1.1929107 , -0.48913106],
        [-1.2921011 ,  0.02912468,  0.3468095 , -1.1626768 ,  0.72603595,
         -1.513555  ,  0.478066  ,  0.9495464 , -2.1072123 ,  0.5262236 ],
        [ 0.41153514, -0.327419  , -0.09706535, -0.03884021,  0.00348211,
          0.13456714,  0.22701445, -0.29304636, -0.10003434,  0.04928138]],
       dtype=float32)>,
 <tf.Variable 'dense_10/bias:0' shape=(10,) dtype=float32, numpy=
 array([0.02019941, 0.0638862 , 0.03949377, 0.09218431, 0.04148377,
        0.13937685, 0.0686149 , 0.06692505, 0.09111057, 0.06604263],
       dtype=float32)>,
 <tf.Variable 'dense_11/kernel:0' shape=(10, 8) dtype=float32, numpy=
 array([[-0.62220913, -0.24139568,  0.30076963, -0.07695704, -0.05111283,
         -0.12970269,  0.01745236, -0.21281299],
        [ 0.27390823,  0.00855141,  0.

In [92]:
model.save("C:/Users/histan/Desktop/NTU AI Program/AI Lab/Lesson4 20210803")

INFO:tensorflow:Assets written to: C:/Users/histan/Desktop/NTU AI Program/AI Lab/Lesson4 20210803\assets
