In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("C:/Users/histan/Desktop/LoanDefault (balance).csv")

In [8]:
print(df)

       student      balance        income  default
0          NaN  729.5264952  4.436163e+04        0
1          1.0          ABC  1.210613e+04        0
2          0.0  1073.549164  8.888890e+12        0
3          0.0  529.2506047  3.570449e+04        0
4          0.0  785.6558829  3.846350e+04        0
...        ...          ...           ...      ...
19329      0.0  2023.901815  2.336643e+04        1
19330      0.0  1231.256092  2.169937e+04        1
19331      0.0  2148.039015  3.693049e+04        1
19332      0.0  1997.068621  3.911978e+04        1
19333      0.0  1568.574866  4.886590e+04        1

[19334 rows x 4 columns]


In [9]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex

In [10]:
df = df.loc[:,["student","balance","income","default"]]

In [14]:
print(df)

       student      balance        income  default
1          1.0          ABC  1.210613e+04        0
2          0.0  1073.549164  8.888890e+12        0
3          0.0  529.2506047  3.570449e+04        0
4          0.0  785.6558829  3.846350e+04        0
5          1.0  919.5885305  7.491559e+03        0
...        ...          ...           ...      ...
19329      0.0  2023.901815  2.336643e+04        1
19330      0.0  1231.256092  2.169937e+04        1
19331      0.0  2148.039015  3.693049e+04        1
19332      0.0  1997.068621  3.911978e+04        1
19333      0.0  1568.574866  4.886590e+04        1

[19333 rows x 4 columns]


In [15]:
df = df.dropna()

In [16]:
print(df)

       student      balance        income  default
1          1.0          ABC  1.210613e+04        0
2          0.0  1073.549164  8.888890e+12        0
3          0.0  529.2506047  3.570449e+04        0
4          0.0  785.6558829  3.846350e+04        0
5          1.0  919.5885305  7.491559e+03        0
...        ...          ...           ...      ...
19329      0.0  2023.901815  2.336643e+04        1
19330      0.0  1231.256092  2.169937e+04        1
19331      0.0  2148.039015  3.693049e+04        1
19332      0.0  1997.068621  3.911978e+04        1
19333      0.0  1568.574866  4.886590e+04        1

[19333 rows x 4 columns]


In [17]:
for i in df.columns:
    print(i)

student
balance
income
default


In [18]:
for i in df.columns:
    df1 = pd.to_numeric(df[i],errors="coerce")
    print(df1)
    df = df[df1.notnull()]

1        1.0
2        0.0
3        0.0
4        0.0
5        1.0
        ... 
19329    0.0
19330    0.0
19331    0.0
19332    0.0
19333    0.0
Name: student, Length: 19333, dtype: float64
1                NaN
2        1073.549164
3         529.250605
4         785.655883
5         919.588531
            ...     
19329    2023.901815
19330    1231.256092
19331    2148.039015
19332    1997.068621
19333    1568.574866
Name: balance, Length: 19333, dtype: float64
2        8.888890e+12
3        3.570449e+04
4        3.846350e+04
5        7.491559e+03
6        2.490523e+04
             ...     
19329    2.336643e+04
19330    2.169937e+04
19331    3.693049e+04
19332    3.911978e+04
19333    4.886590e+04
Name: income, Length: 19332, dtype: float64
2        0
3        0
4        0
5        0
6        0
        ..
19329    1
19330    1
19331    1
19332    1
19333    1
Name: default, Length: 19332, dtype: int64


In [19]:
print(df)

       student      balance        income  default
2          0.0  1073.549164  8.888890e+12        0
3          0.0  529.2506047  3.570449e+04        0
4          0.0  785.6558829  3.846350e+04        0
5          1.0  919.5885305  7.491559e+03        0
6          0.0  825.5133305  2.490523e+04        0
...        ...          ...           ...      ...
19329      0.0  2023.901815  2.336643e+04        1
19330      0.0  1231.256092  2.169937e+04        1
19331      0.0  2148.039015  3.693049e+04        1
19332      0.0  1997.068621  3.911978e+04        1
19333      0.0  1568.574866  4.886590e+04        1

[19332 rows x 4 columns]


In [20]:
import numpy as np

In [22]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [23]:
from scipy import stats

In [24]:
dir(stats)

['F_onewayBadInputSizesWarning',
 'F_onewayConstantInputWarning',
 'PearsonRConstantInputWarning',
 'PearsonRNearConstantInputWarning',
 'SpearmanRConstantInputWarning',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_binned_statistic',
 '_constants',
 '_continuous_distns',
 '_discrete_distns',
 '_distn_infrastructure',
 '_distr_params',
 '_hypotests',
 '_ksstats',
 '_multivariate',
 '_rvs_sampling',
 '_stats',
 '_stats_mstats_common',
 '_tukeylambda_stats',
 '_wilcoxon_data',
 'alpha',
 'anderson',
 'anderson_ksamp',
 'anglit',
 'ansari',
 'arcsine',
 'argus',
 'bartlett',
 'bayes_mvs',
 'bernoulli',
 'beta',
 'betabinom',
 'betaprime',
 'binned_statistic',
 'binned_statistic_2d',
 'binned_statistic_dd',
 'binom',
 'binom_test',
 'boltzmann',
 'boxcox',
 'boxcox_llf',
 'boxcox_normmax',
 'boxcox_normplot',
 'bradford',
 'brunnermunzel',
 'burr',
 'burr12',
 'cauchy',
 'chi',
 'chi2',
 'chi2_c

In [27]:
z = stats.zscore(df.astype(np.float))

<ipython-input-27-93546453b09b>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  z = stats.zscore(df.astype(np.float))


In [28]:
print(z)

[[-6.71583609e-01 -3.33670188e-01  1.39035967e+02 -1.00010346e+00]
 [-6.71583609e-01 -1.22971326e+00 -7.19233839e-03 -1.00010346e+00]
 [-6.71583609e-01 -8.07610045e-01 -7.19229523e-03 -1.00010346e+00]
 ...
 [-6.71583609e-01  1.43519209e+00 -7.19231921e-03  9.99896550e-01]
 [-6.71583609e-01  1.18665942e+00 -7.19228496e-03  9.99896550e-01]
 [-6.71583609e-01  4.81258209e-01 -7.19213251e-03  9.99896550e-01]]


In [29]:
az = np.abs(z)

In [30]:
print(az)

[[6.71583609e-01 3.33670188e-01 1.39035967e+02 1.00010346e+00]
 [6.71583609e-01 1.22971326e+00 7.19233839e-03 1.00010346e+00]
 [6.71583609e-01 8.07610045e-01 7.19229523e-03 1.00010346e+00]
 ...
 [6.71583609e-01 1.43519209e+00 7.19231921e-03 9.99896550e-01]
 [6.71583609e-01 1.18665942e+00 7.19228496e-03 9.99896550e-01]
 [6.71583609e-01 4.81258209e-01 7.19213251e-03 9.99896550e-01]]


In [31]:
f = (az<7).all(axis=1)

In [32]:
print(f)

[False  True  True ...  True  True  True]


In [33]:
df = df[f]

In [34]:
print(df)

       student      balance        income  default
3          0.0  529.2506047  35704.493940        0
4          0.0  785.6558829  38463.495880        0
5          1.0  919.5885305   7491.558572        0
6          0.0  825.5133305  24905.226580        0
7          1.0  808.6675043  17600.451340        0
...        ...          ...           ...      ...
19329      0.0  2023.901815  23366.434730        1
19330      0.0  1231.256092  21699.368770        1
19331      0.0  2148.039015  36930.485540        1
19332      0.0  1997.068621  39119.776760        1
19333      0.0  1568.574866  48865.897080        1

[19331 rows x 4 columns]
