In [82]:
print(df)
timesteps = 4
df_size = 10000 # datasize selected must have both attack and normal data.
df_resize = int(df_size//timesteps) #data_size/timesteps using // because round down, example 10/3=3
df_trunc_size = df_resize * timesteps # remove extra rows for so that data can be divided by timesteps


num_classes = timesteps # follow timestep
# load dataset
import pandas as pd
df = pd.read_csv("C:/Users/histan/Desktop/NTU AI Program/AI Lab/Lesson5 20210805/CyberSecurity.csv")
df_dim = len(df.columns)-1
print(df)


        FIT101    LIT101   MV101  P101  P102    AIT201    AIT202    AIT203  \
0     2.427057  522.8467       2     2     1  262.0161  8.396437  328.6337   
1     2.446274  522.8860       2     2     1  262.0161  8.396437  328.6337   
2     2.489191  522.8467       2     2     1  262.0161  8.394514  328.6337   
3     2.534350  522.9645       2     2     1  262.0161  8.394514  328.6337   
4     2.569260  523.4748       2     2     1  262.0161  8.394514  328.6337   
...        ...       ...     ...   ...   ...       ...       ...       ...   
9995  0.000000  810.6872       1     1     1  263.5222  8.439375  316.7906   
9996  0.000000  810.6479       1     1     1  263.5222  8.439375  316.7906   
9997  0.000000  810.8442       1     1     1  263.5222  8.439375  316.7906   
9998  0.000000  811.0012       1     1     1  263.5222  8.439375  316.7906   
9999  0.000000  810.6872       1     1     1  263.5222  8.439375  316.7906   

        FIT201  Attack  
0     2.445391       0  
1     2.44539

In [83]:
X = df.iloc[:,0:df_dim].values
Y = df.iloc[:,df_dim].values

# Reduce the size of data so that the data can be divided by time step
# split into input (X) and output (Y) variables
X = X[:df_trunc_size,0:df_dim]
Y = Y[:df_trunc_size]

# required format for lstm
X_shaped = X.reshape(df_resize, timesteps, df_dim) 
Y_shaped = Y.reshape(df_resize,timesteps)

print(X_shaped.shape)
print(Y_shaped.shape)


(2500, 4, 9)
(2500, 4)


In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_shaped, Y_shaped, test_size=0.3)


print(X_train, X_test, Y_train, Y_test)

[[[  2.584953 531.9534     2.       ...   8.395475 327.9159     2.443597]
  [  2.566057 532.1497     2.       ...   8.395475 327.9159     2.443982]
  [  2.551645 532.3066     2.       ...   8.395475 327.9159     2.445007]
  [  2.532108 532.4637     2.       ...   8.395475 327.9159     2.443085]]

 [[  2.540435 663.2931     2.       ...   8.438414 318.303      0.      ]
  [  2.540435 663.7642     2.       ...   8.438414 318.303      0.      ]
  [  2.548121 664.1567     2.       ...   8.438414 318.303      0.      ]
  [  2.548121 664.7847     2.       ...   8.438414 318.1236     0.      ]]

 [[  2.425456 508.5195     2.       ...   8.380735 328.4286     2.424375]
  [  2.446274 508.5195     2.       ...   8.380735 328.4286     2.424375]
  [  2.446274 508.5195     2.       ...   8.380735 328.4286     2.424375]
  [  2.495276 508.1662     2.       ...   8.380735 328.4286     2.424375]]

 ...

 [[  2.491112 513.7401     2.       ...   8.380095 328.5312     2.425784]
  [  2.471896 513.4261    

In [85]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, SimpleRNN, GRU, Dropout


In [86]:
model = Sequential()
model.add(LSTM(10, return_sequences=True, input_shape=(timesteps, df_dim)))


In [87]:
model.add(Dropout(0.2))


In [88]:
model.add(LSTM(10, return_sequences=True))

In [89]:
model.add(Dropout(0.2))

In [90]:
model.add(LSTM(10))  

In [91]:
model.add(Dropout(0.2))

In [92]:
model.add(Dense(num_classes,activation="sigmoid"))

In [93]:
model.summary()


Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_21 (LSTM)               (None, 4, 10)             800       
_________________________________________________________________
dropout_19 (Dropout)         (None, 4, 10)             0         
_________________________________________________________________
lstm_22 (LSTM)               (None, 4, 10)             840       
_________________________________________________________________
dropout_20 (Dropout)         (None, 4, 10)             0         
_________________________________________________________________
lstm_23 (LSTM)               (None, 10)                840       
_________________________________________________________________
dropout_21 (Dropout)         (None, 10)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 4)               

In [94]:
model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [95]:
model.fit(X_train, Y_train, batch_size=100, epochs = 20)

Epoch 1/20
18/18 [==============================] - 0s 5ms/step - loss: 0.6788 - accuracy: 0.4034
Epoch 2/20
18/18 [==============================] - 0s 4ms/step - loss: 0.6466 - accuracy: 0.4594
Epoch 3/20
18/18 [==============================] - 0s 4ms/step - loss: 0.6131 - accuracy: 0.4229
Epoch 4/20
18/18 [==============================] - 0s 4ms/step - loss: 0.5930 - accuracy: 0.4131
Epoch 5/20
18/18 [==============================] - 0s 4ms/step - loss: 0.5801 - accuracy: 0.3800
Epoch 6/20
18/18 [==============================] - 0s 4ms/step - loss: 0.5703 - accuracy: 0.3297
Epoch 7/20
18/18 [==============================] - 0s 4ms/step - loss: 0.5563 - accuracy: 0.3394
Epoch 8/20
18/18 [==============================] - 0s 4ms/step - loss: 0.5423 - accuracy: 0.3309
Epoch 9/20
18/18 [==============================] - 0s 4ms/step - loss: 0.5368 - accuracy: 0.3131
Epoch 10/20
18/18 [==============================] - 0s 4ms/step - loss: 0.5236 - accuracy: 0.2943
Epoch 11/20
18/18 [

In [96]:
from sklearn.metrics import confusion_matrix

pred = model.predict(X_test)
# proba is the probability. Here we set threshold as 0.5 to be considered true.
pred = pred > 0.5
# Reshape to a single dimension for comparison and to create confusion matrix
pred = pred.reshape(pred.shape[0]*pred.shape[1])
actual = Y_test.reshape(Y_test.shape[0]*Y_test.shape[1])
cm = confusion_matrix(actual, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))
print(accuracy)


[[2185   17]
 [ 526  272]]
0.819


In [97]:
model = Sequential()
model.add(GRU(12, return_sequences=True, input_shape=(timesteps, df_dim)))
model.add(Dropout(0.2))
model.add(GRU(12,return_sequences=True))
model.add(Dropout(0.2))
model.add(GRU(12))  # return a single vector of dimension 40
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='sigmoid'))
model.summary()
model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

# Train the model
model.fit(X_train, Y_train, batch_size=100, epochs = 20)


Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
gru_3 (GRU)                  (None, 4, 12)             828       
_________________________________________________________________
dropout_22 (Dropout)         (None, 4, 12)             0         
_________________________________________________________________
gru_4 (GRU)                  (None, 4, 12)             936       
_________________________________________________________________
dropout_23 (Dropout)         (None, 4, 12)             0         
_________________________________________________________________
gru_5 (GRU)                  (None, 12)                936       
_________________________________________________________________
dropout_24 (Dropout)         (None, 12)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 4)               

In [98]:
pred = model.predict(X_test)

# proba is the probability. Here we set threshold as 0.5 to be considered true.
pred = pred > 0.35
# Reshape to a single dimension for comparison and to create confusion matrix
pred = pred.reshape(pred.shape[0]*pred.shape[1])
actual = Y_test.reshape(Y_test.shape[0]*Y_test.shape[1])
cm = confusion_matrix(actual, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))
print(accuracy)


[[2178   24]
 [ 530  268]]
0.8153333333333334


In [99]:
model = Sequential()
model.add(SimpleRNN(12, return_sequences=True, input_shape=(timesteps, df_dim)))
model.add(Dropout(0.2))
model.add(SimpleRNN(12, return_sequences=True))
model.add(Dropout(0.2))
model.add(SimpleRNN(12))  # return a single vector of dimension 40
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='sigmoid'))
model.summary()
model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

# Train the model
model.fit(X_train, Y_train, batch_size=100, epochs = 20)


Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_3 (SimpleRNN)     (None, 4, 12)             264       
_________________________________________________________________
dropout_25 (Dropout)         (None, 4, 12)             0         
_________________________________________________________________
simple_rnn_4 (SimpleRNN)     (None, 4, 12)             300       
_________________________________________________________________
dropout_26 (Dropout)         (None, 4, 12)             0         
_________________________________________________________________
simple_rnn_5 (SimpleRNN)     (None, 12)                300       
_________________________________________________________________
dropout_27 (Dropout)         (None, 12)                0         
_________________________________________________________________
dense_5 (Dense)              (None, 4)               

In [100]:
pred = model.predict(X_test)

# proba is the probability. Here we set threshold as 0.5 to be considered true.
pred = pred > 0.25
# Reshape to a single dimension for comparison and to create confusion matrix
pred = pred.reshape(pred.shape[0]*pred.shape[1])
actual = Y_test.reshape(Y_test.shape[0]*Y_test.shape[1])
cm = confusion_matrix(actual, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))
print(accuracy)


[[2185   17]
 [ 526  272]]
0.819
